-- AlterTable
ALTER TABLE "Message" ADD COLUMN     "isReply" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "msgType" TEXT NOT NULL DEFAULT 'text',
ADD COLUMN     "replyMsgId" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Message" ADD CONSTRAINT "Message_replyMsgId_fkey" FOREIGN KEY ("replyMsgId") REFERENCES "Message"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
